import Head from "next/head";

const Header = () => {
  return (
    <>
     <Head>
        <title>Fajar Abdurrohman Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
    </>
  )
}

export default Header